import test from 'node:test';import assert from 'node:assert/strict';
import {blankProject,makeLayer,validateProject,setKey,valueAt} from '../src/core.js';
import {splitClip,moveClip,trimClip} from '../src/media-core.js';
import {mimeFor,MAX_ASSET_BYTES,MAX_TOTAL_BYTES} from '../src/assets.js';
function project(){const p=blankProject();p.duration=20;const a={id:'asset-'+'a'.repeat(64),name:'Original synthetic fixture',mime:'video/mp4',type:'video',size:1200,duration:10,width:320,height:180};p.assets=[a];p.layers=[Object.assign(makeLayer('video',10),{assetId:a.id,mediaDuration:10,sourceIn:0,volume:1,muted:false,fadeIn:.5,fadeOut:.5})];return p;}
test('schema v3 round-trips video/audio sources without external URLs',()=>{const p=project();assert.deepEqual(validateProject(p),p);const a=structuredClone(p.layers[0]);a.id='audio';a.type='audio';a.name='Detached original tone';p.layers.push(a);assert.deepEqual(validateProject(p),p);});
test('trim/split/move project retains off-screen motion keys and fade envelope',()=>{const p=project(),l=p.layers[0];setKey(l,'x',0,0,'bezier',[.8,0,.8,1]);setKey(l,'x',10,100);p.layers=splitClip(l,5,'other');p.layers[1]=moveClip(p.layers[1],0,20);const next=validateProject(p);assert.equal(next.layers[1].keys.x[0].time,-5);assert.equal(next.layers[1].fadeOrigin.duration,10);assert.equal(valueAt(next.layers[1],'x',0),valueAt(l,'x',5));});
test('source bounds, unavailable assets and hostile data are rejected',()=>{let p=project();p.layers[0].sourceIn=2;assert.throws(()=>validateProject(p));p=project();p.assets=[];assert.throws(()=>validateProject(p));p=project();p.assets[0].data='https://example.com/private.mp4';assert.throws(()=>validateProject(p));p=project();p.assets[0].mime='text/html';assert.throws(()=>validateProject(p));p=project();p.assets[0].id='__proto__';assert.throws(()=>validateProject(p));});
test('media size limits and source mime fallback are explicit',()=>{assert.equal(MAX_ASSET_BYTES,64*1024*1024);assert.equal(MAX_TOTAL_BYTES,128*1024*1024);assert.equal(mimeFor({name:'clip.mp4',type:''}),'video/mp4');assert.equal(mimeFor({name:'tone.wav',type:'audio/wav'}),'audio/wav');assert.throws(()=>mimeFor({name:'x.html',type:'text/html'}));const p=project();p.assets[0].size=MAX_ASSET_BYTES+1;assert.throws(()=>validateProject(p));});
