import {PROPERTIES, EASINGS, clone, clamp, uid, makeLayer, blankProject, sampleProject, validateProject, setKey, valueAt, evaluated, History} from './core.js';
import {drawProject,loadImages,hitTest,images} from './render.js';
import {GifEncoder} from './gif.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={x:'位置 X',y:'位置 Y',scale:'缩放',rotation:'旋转',opacity:'不透明度',blur:'模糊'};
const icons={text:'T',rect:'▢',ellipse:'◯',image:'▧'};
const easeLabels={linear:'线性',easeIn:'缓入',easeOut:'缓出',easeInOut:'缓入缓出',hold:'保持'};
const ranges={x:[-20000,20000,1],y:[-20000,20000,1],scale:[.01,20,.01],rotation:[-36000,36000,1],opacity:[0,1,.01],blur:[0,100,1]};
const history=new History();let project=sampleProject(),selected=null,time=1.7,playing=false,loop=true,autoKey=false,selectedKey=null,zoom=1,exporting=false,cancelExport=false,dirty=false,storageTimer,toastTimer,lastTick=0;
const canvas=$('#canvas'),ctx=canvas.getContext('2d');const STORAGE='filisi-motion-autosave-v1';
try{const saved=localStorage.getItem(STORAGE);if(saved){project=validateProject(JSON.parse(saved));time=0;}}catch{toast('未能恢复自动存档，已载入示例。');}
selected=project.layers.find(l=>l.type==='text')?.id??project.layers.at(-1)?.id??null;
const layer=()=>project.layers.find(l=>l.id===selected);
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3400);}
function checkpoint(){history.push(project);}
function changed({panels=true}={}){dirty=true;$('#save-state').textContent='正在本地保存…';clearTimeout(storageTimer);storageTimer=setTimeout(()=>{try{localStorage.setItem(STORAGE,JSON.stringify(project));$('#save-state').textContent='已自动保存到此浏览器';}catch{$('#save-state').textContent='自动存档空间不足 · 请保存工程';}},350);if(panels)renderUI();else{renderCanvas();renderTimeline();updateHistory();}}
function updateHistory(){$('#undo').disabled=!history.past.length;$('#redo').disabled=!history.future.length;}
function renderCanvas(){drawProject(ctx,project,time,{selected:playing?null:selected});$('#time-display').textContent=formatTime(time);positionPlayhead();}
function formatTime(t){const f=Math.round(t*project.fps);return`${String(Math.floor(f/project.fps/60)).padStart(2,'0')}:${String(Math.floor(f/project.fps)%60).padStart(2,'0')}:${String(f%project.fps).padStart(2,'0')}`;}
function resizeCanvas(){canvas.width=project.width;canvas.height=project.height;const wrap=$('#stage-wrap');const fit=Math.min((wrap.clientWidth-64)/project.width,(wrap.clientHeight-62)/project.height,1);const factor=$('#preview-scale').value==='fit'?Math.max(.05,fit):Number($('#preview-scale').value);$('#stage').style.width=`${project.width*factor}px`;$('#stage').style.height=`${project.height*factor}px`;renderCanvas();}
function renderUI(){if(selected&&!layer())selected=null;$('#project-name').value=project.name;$('#viewer-name').textContent=project.name;for(const p of ['width','height','duration','fps','background'])$(`#comp-${p}`).value=project[p];$('#comp-info').textContent=`${project.width} × ${project.height} / ${project.fps} fps`;$('#layer-count').textContent=`${project.layers.length} 个图层`;updateHistory();renderInspector();renderTimeline();resizeCanvas();}
function select(id){selected=id;selectedKey=null;renderInspector();renderTimeline();renderCanvas();}
function setTime(t,{inspector=true}={}){time=clamp(Math.round(t*project.fps)/project.fps,0,project.duration);renderCanvas();if(inspector)renderInspector();}
function stop(){playing=false;$('#play').textContent='▶';$('#play').setAttribute('aria-label','播放');}
function togglePlay(){if(exporting)return;if(playing){stop();renderCanvas();renderInspector();return;}if(time>=project.duration)time=0;playing=true;lastTick=performance.now();$('#play').textContent='Ⅱ';$('#play').setAttribute('aria-label','暂停');requestAnimationFrame(tick);}
function tick(now){if(!playing)return;time+=(now-lastTick)/1000;lastTick=now;if(time>=project.duration){if(loop)time%=project.duration;else{time=project.duration;stop();renderInspector();}}renderCanvas();if(playing)requestAnimationFrame(tick);}
function mutateLayer(fn){stop();const l=layer();if(!l)return;if(l.locked){toast('图层已锁定，请先解锁。');return;}checkpoint();fn(l);selectedKey=null;changed();}
function animatedChange(l,p,value){if(autoKey||l.keys[p]?.length)setKey(l,p,time,value,l.keys[p]?.find(k=>Math.abs(k.time-time)<.0001)?.easing??'easeInOut');else l[p]=value;}
function renderInspector(){const l=layer();const body=$('#inspector-body');if(!l){body.innerHTML='<div class="empty">选择一个图层，<br>开始调整它的样子与运动。<br><br>点击左侧工具添加素材，<br>或直接点击画布中的对象。</div>';return;}
 const val=p=>Math.round(valueAt(l,p,time)*1000)/1000;
 const field=(p,label,min,max,step=1)=>`<label>${label}<input data-basic="${p}" type="number" value="${l[p]}" min="${min}" max="${max}" step="${step}" ${l.locked?'disabled':''}></label>`;
 body.innerHTML=`<div class="layer-heading"><span class="layer-icon">${icons[l.type]}</span><input id="layer-name" aria-label="图层名称" value="${esc(l.name)}" maxlength="120" ${l.locked?'disabled':''}></div>${l.locked?'<p class="locked-notice">此图层已锁定。</p>':''}${l.type==='text'?`<label>文字内容<textarea id="text-content" ${l.locked?'disabled':''}>${esc(l.text)}</textarea></label><div class="form-grid" style="margin-top:10px">${field('fontSize','字号',1,1000)}<label>字重<select id="font-weight" ${l.locked?'disabled':''}>${[400,500,600,700,800,900].map(n=>`<option value="${n}" ${l.fontWeight===n?'selected':''}>${n}</option>`).join('')}</select></label><label class="span2">对齐<select id="text-align" ${l.locked?'disabled':''}>${[['left','左对齐'],['center','居中'],['right','右对齐']].map(([v,n])=>`<option value="${v}" ${l.align===v?'selected':''}>${n}</option>`).join('')}</select></label></div>`:''}
 <div class="section-title">变换 <span>◇ 添加 / 删除当前关键帧</span></div>${PROPERTIES.map(p=>`<div class="prop-row"><label for="prop-${p}">${labels[p]}${p==='scale'||p==='opacity'?' ×':''}</label><input id="prop-${p}" data-property="${p}" type="number" min="${ranges[p][0]}" max="${ranges[p][1]}" step="${ranges[p][2]}" value="${val(p)}" ${l.locked?'disabled':''}><button data-key="${p}" class="key-toggle ${l.keys[p]?.length?'animated':''} ${l.keys[p]?.some(k=>Math.abs(k.time-time)<.0001)?'current':''}" title="${labels[p]}：添加或删除当前关键帧" aria-label="${labels[p]}关键帧" ${l.locked?'disabled':''}>◇</button></div>`).join('')}
 <div class="section-title">外观与时间</div><div class="form-grid">${field('width','宽度',1,20000)}${field('height','高度',1,20000)}${l.type==='rect'?field('radius','圆角',0,2000):''}${l.type!=='image'?`<label class="color-label">填充<input id="layer-fill" type="color" value="${l.fill}" ${l.locked?'disabled':''}></label>`:''}${field('start','入点 / 秒',0,project.duration,.01)}${field('end','出点 / 秒',0,project.duration,.01)}<label class="span2">混合模式<select id="blend-mode" ${l.locked?'disabled':''}>${[['source-over','正常'],['multiply','正片叠底'],['screen','滤色'],['overlay','叠加'],['lighter','相加']].map(([v,n])=>`<option value="${v}" ${l.blend===v?'selected':''}>${n}</option>`).join('')}</select></label></div>
 <div class="layer-controls"><button id="duplicate-layer">复制</button><button id="move-up" ${l.locked?'disabled':''}>上移</button><button id="move-down" ${l.locked?'disabled':''}>下移</button><button id="lock-layer">${l.locked?'解锁':'锁定'}</button><button id="delete-layer" class="danger" ${l.locked?'disabled':''}>删除</button></div><div id="key-editor"></div>`;
 $('#layer-name').onchange=e=>mutateLayer(l=>{l.name=e.target.value.trim()||'未命名图层';});
 for(const input of $$('[data-property]')) input.onchange=e=>{const p=e.target.dataset.property,n=Number(e.target.value);if(!Number.isFinite(n)||e.target.value===''){renderInspector();return;}mutateLayer(l=>animatedChange(l,p,clamp(n,...ranges[p])));};
 for(const button of $$('[data-key]'))button.onclick=()=>mutateLayer(l=>{const p=button.dataset.key;const list=l.keys[p]??[];const i=list.findIndex(k=>Math.abs(k.time-time)<.0001);if(i>=0){const current=valueAt(l,p,time);list.splice(i,1);if(!list.length)l[p]=current;}else setKey(l,p,time,valueAt(l,p,time));});
 for(const input of $$('[data-basic]'))input.onchange=e=>{const p=e.target.dataset.basic,n=Number(e.target.value);if(!Number.isFinite(n)||e.target.value===''){renderInspector();return;}const value=clamp(n,Number(input.min),Number(input.max));if((p==='start'&&value>=l.end)||(p==='end'&&value<=l.start)){toast('出点必须晚于入点。');renderInspector();return;}mutateLayer(l=>{l[p]=value;});};
 if(l.type==='text'){$('#text-content').onchange=e=>mutateLayer(l=>{l.text=e.target.value.slice(0,4000);});$('#font-weight').onchange=e=>mutateLayer(l=>{l.fontWeight=Number(e.target.value);});$('#text-align').onchange=e=>mutateLayer(l=>{l.align=e.target.value;});}
 if($('#layer-fill'))$('#layer-fill').onchange=e=>mutateLayer(l=>{l.fill=e.target.value;});
 $('#blend-mode').onchange=e=>mutateLayer(l=>{l.blend=e.target.value;});$('#duplicate-layer').onclick=duplicateLayer;$('#delete-layer').onclick=deleteSelection;$('#move-up').onclick=()=>reorder(1);$('#move-down').onclick=()=>reorder(-1);$('#lock-layer').onclick=()=>{checkpoint();l.locked=!l.locked;changed();};
 if(selectedKey&&selectedKey.layer===l.id){const k=l.keys[selectedKey.property]?.find(k=>k.time===selectedKey.time);if(!k){selectedKey=null;return;}
 $('#key-editor').innerHTML=`<div class="selected-key"><div class="section-title">已选关键帧 · ${labels[selectedKey.property]}</div><label>时间 / 秒<input id="key-time" type="number" min="0" max="${project.duration}" step="${1/project.fps}" value="${k.time}" ${l.locked?'disabled':''}></label><label>数值<input id="key-value" type="number" step="any" value="${k.value}" ${l.locked?'disabled':''}></label><label>到下一帧的缓动<select id="key-easing" ${l.locked?'disabled':''}>${Object.entries(easeLabels).map(([v,n])=>`<option value="${v}" ${k.easing===v?'selected':''}>${n}</option>`).join('')}</select></label><button id="delete-key" class="danger" ${l.locked?'disabled':''}>删除关键帧</button></div>`;
 $('#key-easing').onchange=e=>{checkpoint();k.easing=e.target.value;changed();};$('#key-value').onchange=e=>{const v=Number(e.target.value);if(!Number.isFinite(v)){renderInspector();return;}checkpoint();k.value=clamp(v,...ranges[selectedKey.property]);changed();};
 $('#key-time').onchange=e=>{const value=Number(e.target.value);if(!Number.isFinite(value)){renderInspector();return;}checkpoint();const keys=l.keys[selectedKey.property];keys.splice(keys.indexOf(k),1);const t=clamp(Math.round(value*project.fps)/project.fps,0,project.duration);setKey(l,selectedKey.property,t,k.value,k.easing);selectedKey.time=t;time=t;changed();};$('#delete-key').onclick=deleteSelection;
 }
}
function positionPlayhead(){const line=$('.playhead'),track=$('.ruler .tl-track');if(!line||!track)return;line.style.left=`${track.offsetLeft+time/project.duration*track.clientWidth}px`;}
function renderTimeline(){const content=$('#timeline-content');const width=Math.max($('#timeline-scroll').clientWidth,540)*zoom;content.style.width=`${width}px`;let html=`<div class="tl-row ruler"><div class="tl-label">图层 / ${project.fps} FPS</div><div class="tl-track" data-ruler>${Array.from({length:11},(_,i)=>`<span class="tick" style="left:${i*10}%">${Number((project.duration*i/10).toFixed(2))}s</span>`).join('')}</div></div>`;
 for(const l of [...project.layers].reverse()){
 html+=`<div class="tl-row ${l.id===selected?'selected':''}" data-layer="${esc(l.id)}"><div class="tl-label"><button data-visibility="${esc(l.id)}" title="${l.visible?'隐藏':'显示'}图层" aria-label="${l.visible?'隐藏':'显示'}${esc(l.name)}">${l.visible?'◉':'○'}</button><span class="type">${icons[l.type]}</span><span class="name">${esc(l.name)}</span><button data-lock="${esc(l.id)}" title="${l.locked?'解锁':'锁定'}图层" aria-label="${l.locked?'解锁':'锁定'}${esc(l.name)}">${l.locked?'▣':'□'}</button></div><div class="tl-track"><div class="tl-bar" data-bar="${esc(l.id)}" style="left:${l.start/project.duration*100}%;width:${(l.end-l.start)/project.duration*100}%;opacity:${l.visible?1:.35}"><span class="trim left" data-trim="start"></span><span class="trim right" data-trim="end"></span></div></div></div>`;
 if(selected===l.id) for(const p of PROPERTIES){if(!l.keys[p]?.length)continue;html+=`<div class="tl-row property-row"><div class="tl-label">◇ ${labels[p]}</div><div class="tl-track">${l.keys[p].map(k=>`<button class="diamond ${selectedKey?.property===p&&selectedKey.time===k.time?'active':''}" data-key-property="${p}" data-key-time="${k.time}" title="${labels[p]} · ${k.time.toFixed(2)} 秒 · ${k.value}" aria-label="${labels[p]} ${k.time.toFixed(2)} 秒关键帧" style="left:${k.time/project.duration*100}%"></button>`).join('')}</div></div>`;}
 }
 content.innerHTML=html+(project.layers.length?'':'<div class="empty-timeline">还没有图层。添加一段文字，试着让它动起来。</div>')+'<div class="playhead"></div>';
 for(const row of $$('[data-layer]'))row.querySelector('.tl-label').onclick=e=>{if(!e.target.closest('button'))select(row.dataset.layer);};
 for(const b of $$('[data-visibility]'))b.onclick=()=>{checkpoint();const l=project.layers.find(l=>l.id===b.dataset.visibility);l.visible=!l.visible;changed();};
 for(const b of $$('[data-lock]'))b.onclick=()=>{checkpoint();const l=project.layers.find(l=>l.id===b.dataset.lock);l.locked=!l.locked;changed();};
 $('[data-ruler]').onpointerdown=e=>{if(e.button!==0)return;stop();selectedKey=null;const rect=e.currentTarget.getBoundingClientRect();const move=e=>setTime((e.clientX-rect.left)/rect.width*project.duration);move(e);trackPointer(e,move,()=>renderInspector());};
 for(const bar of $$('[data-bar]'))bar.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();stop();const l=project.layers.find(l=>l.id===bar.dataset.bar);selected=l.id;selectedKey=null;if(l.locked){renderInspector();renderTimeline();return;}const mode=e.target.dataset.trim,rect=bar.parentElement.getBoundingClientRect(),origin=e.clientX,start=l.start,end=l.end,span=end-start;let pushed=false;
 trackPointer(e,e=>{const dt=Math.round((e.clientX-origin)/rect.width*project.duration*project.fps)/project.fps;if(!pushed&&Math.abs(e.clientX-origin)>2){checkpoint();pushed=true;}if(!pushed)return;if(mode==='start')l.start=clamp(start+dt,0,end-1/project.fps);else if(mode==='end')l.end=clamp(end+dt,start+1/project.fps,project.duration);else{const newStart=clamp(start+dt,0,project.duration-span),shift=newStart-l.start;l.start=newStart;l.end=newStart+span;for(const keys of Object.values(l.keys))for(const k of keys)k.time=clamp(k.time+shift,0,project.duration);}
 bar.style.left=`${l.start/project.duration*100}%`;bar.style.width=`${(l.end-l.start)/project.duration*100}%`;renderCanvas();},()=>{if(pushed)changed();else{renderTimeline();renderInspector();renderCanvas();}});};
 for(const d of $$('[data-key-property]'))d.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();stop();const l=layer(),p=d.dataset.keyProperty,old=Number(d.dataset.keyTime),key=l.keys[p].find(k=>k.time===old);selectedKey={layer:l.id,property:p,time:old};time=old;if(l.locked){renderUI();return;}const rect=d.parentElement.getBoundingClientRect(),x=e.clientX;let pushed=false;
 trackPointer(e,e=>{if(!pushed&&Math.abs(e.clientX-x)>2){checkpoint();pushed=true;}if(!pushed)return;const t=clamp(Math.round((e.clientX-rect.left)/rect.width*project.duration*project.fps)/project.fps,0,project.duration);key.time=t;selectedKey.time=t;time=t;d.style.left=`${t/project.duration*100}%`;renderCanvas();},()=>{if(pushed){const others=l.keys[p].filter(k=>k!==key&&Math.abs(k.time-key.time)>.0001);l.keys[p]=[...others,key].sort((a,b)=>a.time-b.time);changed();}else{renderInspector();renderTimeline();renderCanvas();}});};
 positionPlayhead();
}
function trackPointer(start,move,end){const up=e=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',up);end(e);};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});window.addEventListener('pointercancel',up,{once:true});}
canvas.onpointerdown=e=>{if(e.button!==0||exporting)return;stop();const rect=canvas.getBoundingClientRect();const x=(e.clientX-rect.left)/rect.width*project.width,y=(e.clientY-rect.top)/rect.height*project.height;selected=hitTest(project,time,x,y);selectedKey=null;renderCanvas();renderInspector();renderTimeline();const l=layer();if(!l)return;const ox=valueAt(l,'x',time),oy=valueAt(l,'y',time);let pushed=false;
 trackPointer(e,e=>{const dx=(e.clientX-rect.left)/rect.width*project.width-x,dy=(e.clientY-rect.top)/rect.height*project.height-y;if(!pushed&&Math.hypot(dx,dy)>2){checkpoint();pushed=true;}if(!pushed)return;animatedChange(l,'x',clamp(Math.round(ox+dx),-20000,20000));animatedChange(l,'y',clamp(Math.round(oy+dy),-20000,20000));renderCanvas();},()=>{if(pushed)changed();});};
function addLayer(type){stop();if(project.layers.length>=100){toast('预览版最多支持 100 个图层。');return;}checkpoint();const l=makeLayer(type,project.duration);l.x=project.width/2;l.y=project.height/2;l.width=Math.min(l.width,project.width*.7);l.height=Math.min(l.height,project.height*.7);project.layers.push(l);select(l.id);changed();}
function duplicateLayer(){const l=layer();if(!l)return;if(project.layers.length>=100){toast('已达到 100 个图层上限。');return;}checkpoint();const copy=clone(l);copy.id=uid();copy.name+=' 副本';copy.locked=false;copy.x+=20;copy.y+=20;for(const p of ['x','y'])for(const k of copy.keys[p]??[])k.value+=20;project.layers.splice(project.layers.indexOf(l)+1,0,copy);selected=copy.id;selectedKey=null;changed();}
function deleteSelection(){const l=layer();if(!l||l.locked)return;checkpoint();if(selectedKey?.layer===l.id){const p=selectedKey.property;const current=valueAt(l,p,time);l.keys[p]=l.keys[p].filter(k=>k.time!==selectedKey.time);if(!l.keys[p].length)l[p]=current;selectedKey=null;}else{project.layers=project.layers.filter(v=>v.id!==l.id);selected=project.layers.at(-1)?.id??null;}changed();}
function reorder(delta){mutateLayer(l=>{const i=project.layers.indexOf(l),j=clamp(i+delta,0,project.layers.length-1);project.layers.splice(i,1);project.layers.splice(j,0,l);});}
async function replaceProject(next){stop();try{await loadImages(next);}catch{toast('工程中的图片无法解码，未替换当前工程。');return;}checkpoint();project=next;time=0;selected=project.layers.at(-1)?.id??null;selectedKey=null;images.forEach((_,src)=>{if(!project.layers.some(l=>l.src===src))images.delete(src);});changed();}
function download(blob,filename){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
const filename=()=>project.name.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,100)||'filisi-motion';
function saveProject(){download(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),`${filename()}.filisi`);dirty=false;toast('工程文件已生成，请保留它以便在其他设备打开。');}
$('#add-text').onclick=()=>addLayer('text');$('#add-rect').onclick=()=>addLayer('rect');$('#add-ellipse').onclick=()=>addLayer('ellipse');$('#save-project').onclick=saveProject;$('#open-project').onclick=()=>$('#project-file').click();$('#import-image').onclick=()=>$('#image-file').click();
$('#project-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>40*1024*1024){toast('工程文件超过 40 MB 限制。');return;}try{const next=validateProject(JSON.parse(await file.text()));if(dirty&&!confirm('打开工程会替换当前画布。尚未下载保存的更改可通过撤销恢复，继续吗？'))return;await replaceProject(next);toast('工程已打开。');}catch(err){toast(`无法打开：${err.message}`);}};
$('#image-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(project.layers.length>=100){toast('已达到图层上限。');return;}if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10*1024*1024){toast('请选择 10 MB 以内的 PNG、JPEG 或 WebP 图片。');return;}
 try{const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});const img=new Image();img.src=src;await img.decode();if(img.naturalWidth>12000||img.naturalHeight>12000){toast('图片边长不能超过 12000 像素，请先缩小。');return;}const l=makeLayer('image',project.duration);l.src=src;l.name=file.name;l.x=project.width/2;l.y=project.height/2;const scale=Math.min(project.width*.7/img.naturalWidth,project.height*.7/img.naturalHeight,1);l.width=Math.round(img.naturalWidth*scale);l.height=Math.round(img.naturalHeight*scale);images.set(src,img);checkpoint();project.layers.push(l);selected=l.id;changed();toast('图片已导入，并嵌入工程。');}catch{toast('图片解码失败，请检查文件。');}};
$('#new-project').onclick=()=>{if(!confirm('新建空白工程？当前工程建议先保存，也可通过撤销恢复。'))return;replaceProject(blankProject());};$('#load-sample').onclick=()=>{if(dirty&&!confirm('载入示例将替换当前画布，继续吗？'))return;replaceProject(sampleProject());};
$('#project-name').onchange=e=>{checkpoint();project.name=e.target.value.trim()||'未命名合成';changed();};
for(const prop of ['width','height','duration','fps','background'])$(`#comp-${prop}`).onchange=e=>{const value=prop==='background'?e.target.value:Number(e.target.value);if(prop!=='background'&&(!Number.isFinite(value)||e.target.value==='')){renderUI();return;}const next=clone(project);next[prop]=prop==='background'?value:clamp(prop==='duration'?value:Math.round(value),Number(e.target.min),Number(e.target.max));if(prop==='duration'){for(const l of next.layers){l.start=Math.min(l.start,Math.max(0,next.duration-1/next.fps));l.end=Math.min(l.end,next.duration);if(l.end<=l.start)l.end=next.duration;for(const keys of Object.values(l.keys)){for(const k of keys)k.time=Math.min(k.time,next.duration);}}}
 try{const validated=validateProject(next);checkpoint();project=validated;time=Math.min(time,project.duration);selectedKey=null;changed();}catch(err){toast(err.message);renderUI();}};
for(const b of $$('[data-aspect]'))b.onclick=()=>{checkpoint();[project.width,project.height]=b.dataset.aspect.split(',').map(Number);changed();};
$('#undo').onclick=()=>{stop();project=history.undo(project);time=Math.min(time,project.duration);selectedKey=null;loadImages(project).then(()=>changed()).catch(()=>toast('撤销时图片未能恢复。'));};$('#redo').onclick=()=>{stop();project=history.redo(project);time=Math.min(time,project.duration);selectedKey=null;loadImages(project).then(()=>changed()).catch(()=>toast('重做时图片未能恢复。'));};
$('#play').onclick=togglePlay;$('#go-start').onclick=()=>{stop();setTime(0);};$('#step-back').onclick=()=>{stop();setTime(time-1/project.fps);};$('#step-next').onclick=()=>{stop();setTime(time+1/project.fps);};$('#toggle-loop').onclick=()=>{loop=!loop;$('#toggle-loop').setAttribute('aria-pressed',String(loop));};$('#auto-key').onclick=()=>{autoKey=!autoKey;$('#auto-key').setAttribute('aria-pressed',String(autoKey));};$('#toggle-grid').onclick=()=>{const guide=$('.safe-guides');guide.hidden=!guide.hidden;$('#toggle-grid').setAttribute('aria-pressed',String(!guide.hidden));};$('#preview-scale').onchange=resizeCanvas;$('#timeline-zoom').oninput=e=>{zoom=Number(e.target.value);renderTimeline();};$('#help-open').onclick=()=>$('#help-dialog').showModal();
const recorderType=()=>typeof MediaRecorder==='undefined'?null:['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));
function updateExportNote(){const format=$('#export-format').value;$('#gif-options').hidden=format!=='gif';$('#export-note').textContent=format==='webm'?(recorderType()?`按 ${project.width} × ${project.height}、${project.fps} FPS 实时录制，约需 ${project.duration} 秒。请保持此页面前台可见。无音轨；浏览器繁忙时可能丢帧。`:'此浏览器不支持 WebM 录制，请切换 GIF 或 PNG；也可使用桌面 Chrome / Edge。'):format==='gif'?'逐帧离线渲染，不受实时播放速度影响。固定 256 色，不含音频；文件较大。最多 600 帧、总计 8000 万像素，建议短片用 480 px / 12 FPS。':'导出当前播放头处的 PNG 图像，使用原合成尺寸，不含选框。';$('#export-start').disabled=format==='webm'&&!recorderType();}
$('#export-open').onclick=()=>{stop();$('#export-status').textContent='';$('#export-progress').hidden=true;updateExportNote();$('#export-dialog').showModal();};$('#export-format').onchange=updateExportNote;$('#export-cancel').onclick=()=>{cancelExport=true;};$('#export-dialog').addEventListener('cancel',e=>{if(exporting){e.preventDefault();cancelExport=true;}});$('#export-dialog').querySelector('form').addEventListener('submit',e=>{if(exporting){e.preventDefault();cancelExport=true;}});
const breathe=()=>new Promise(r=>setTimeout(r,0));
async function exportGif(p){const width=Number($('#gif-width').value),height=Math.round(width*p.height/p.width),fps=Number($('#gif-fps').value),count=Math.ceil(p.duration*fps);if(count>600||count*width*height>80000000)throw Error('GIF 超过资源上限，请缩短合成、降低宽度或帧率。');const off=document.createElement('canvas');off.width=width;off.height=height;const c=off.getContext('2d',{willReadFrequently:true}),encoder=new GifEncoder(width,height,fps);
 for(let i=0;i<count;i++){if(cancelExport)throw Error('已取消导出');drawProject(c,p,i/fps,{width,height});encoder.addFrame(c.getImageData(0,0,width,height).data);$('#export-progress').value=(i+1)/count;$('#export-status').textContent=`正在渲染 ${i+1} / ${count} 帧`;if(i%2===0)await breathe();}return encoder.finish();}
async function exportWebm(p){
 const type=recorderType();if(!type)throw Error('此浏览器无法录制 WebM，请使用 GIF。');if(document.hidden)throw Error('请保持此页面在前台后重试。');
 const off=document.createElement('canvas');off.width=p.width;off.height=p.height;const c=off.getContext('2d');drawProject(c,p,0);const stream=off.captureStream(p.fps);let recorder;
 try{recorder=new MediaRecorder(stream,{mimeType:type,videoBitsPerSecond:Math.min(16000000,p.width*p.height*p.fps*.18)});}catch(err){stream.getTracks().forEach(t=>t.stop());throw err;}
 return new Promise((resolve,reject)=>{
  const chunks=[];let error=null,raf=0,finished=false;
  const stopRecording=reason=>{if(finished)return;if(reason)error=Error(reason);if(recorder.state!=='inactive')recorder.stop();};
  const visibility=()=>{if(document.hidden)stopRecording('页面移到后台，录制已停止。请保持前台后重试。');};
  const watchdog=setInterval(()=>{if(cancelExport)stopRecording('已取消导出');},100);
  const cleanup=()=>{finished=true;cancelAnimationFrame(raf);clearInterval(watchdog);document.removeEventListener('visibilitychange',visibility);stream.getTracks().forEach(t=>t.stop());};
  recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};
  recorder.onerror=e=>{error=e.error??Error('视频录制失败');if(recorder.state!=='inactive')recorder.stop();else{cleanup();reject(error);}};
  recorder.onstop=()=>{cleanup();if(error)reject(error);else resolve(new Blob(chunks,{type:'video/webm'}));};
  document.addEventListener('visibilitychange',visibility);
  try{recorder.start(100);}catch(err){cleanup();reject(err);return;}
  const start=performance.now();
  function frame(now){if(finished||recorder.state==='inactive')return;const elapsed=(now-start)/1000;if(cancelExport){stopRecording('已取消导出');return;}
   drawProject(c,p,Math.min(elapsed,p.duration-1/p.fps));$('#export-progress').value=Math.min(1,elapsed/p.duration);$('#export-status').textContent=`正在录制 ${Math.min(elapsed,p.duration).toFixed(1)} / ${p.duration} 秒`;
   if(elapsed>=p.duration)stopRecording();else raf=requestAnimationFrame(frame);
  }raf=requestAnimationFrame(frame);
 });
}
$('#export-start').onclick=async()=>{if(exporting)return;const p=clone(project),format=$('#export-format').value;exporting=true;cancelExport=false;$('#export-start').disabled=true;$('#export-format').disabled=true;$('#export-cancel').hidden=false;$('#export-progress').hidden=false;$('#export-progress').value=0;try{await loadImages(p);let blob;if(format==='png'){const off=document.createElement('canvas');off.width=p.width;off.height=p.height;drawProject(off.getContext('2d'),p,time);blob=await new Promise((resolve,reject)=>off.toBlob(b=>b?resolve(b):reject(Error('PNG 导出失败')),'image/png'));}else blob=format==='gif'?await exportGif(p):await exportWebm(p);if(cancelExport)throw Error('已取消导出');download(blob,`${filename()}.${format}`);$('#export-progress').value=1;$('#export-status').textContent=`导出完成 · ${(blob.size/1024/1024).toFixed(2)} MB · 请检查下载文件`;}catch(err){$('#export-status').textContent=err.message;}finally{exporting=false;$('#export-format').disabled=false;$('#export-cancel').hidden=true;updateExportNote();}};
window.addEventListener('keydown',e=>{if($('dialog[open]')||exporting||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable)return;const mod=e.metaKey||e.ctrlKey;const key=e.key.toLowerCase();if(mod&&['s','o','z','y','d'].includes(key)){e.preventDefault();if(key==='s')saveProject();if(key==='o')$('#project-file').click();if(key==='z')$(e.shiftKey?'#redo':'#undo').click();if(key==='y')$('#redo').click();if(key==='d')duplicateLayer();return;}if(e.code==='Space'){e.preventDefault();togglePlay();}if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();stop();setTime(time+(e.key==='ArrowLeft'?-1:1)*(e.shiftKey?10:1)/project.fps);}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();deleteSelection();}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
new ResizeObserver(()=>{resizeCanvas();renderTimeline();}).observe($('#stage-wrap'));
loadImages(project).then(renderUI).catch(()=>{toast('部分图片无法恢复，请重新导入。');renderUI();});
